// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AnalisisMicrobiologicoEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.AnalisisMicrobiologico",
                typeof(AnalisisMicrobiologico),
                baseEntityType,
                propertyCount: 18,
                navigationCount: 1,
                foreignKeyCount: 1,
                namedIndexCount: 1,
                keyCount: 1);

            var analisisMicroId = runtimeEntityType.AddProperty(
                "AnalisisMicroId",
                typeof(int),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("AnalisisMicroId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<AnalisisMicroId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            analisisMicroId.AddAnnotation("Relational:ColumnName", "analisis_micro_id");
            analisisMicroId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var aptoParaConsumo = runtimeEntityType.AddProperty(
                "AptoParaConsumo",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("AptoParaConsumo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<AptoParaConsumo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            aptoParaConsumo.AddAnnotation("Relational:ColumnName", "apto_para_consumo");
            aptoParaConsumo.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var equipos = runtimeEntityType.AddProperty(
                "Equipos",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("Equipos", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<Equipos>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            equipos.AddAnnotation("Relational:ColumnName", "equipos");
            equipos.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var esCopia = runtimeEntityType.AddProperty(
                "EsCopia",
                typeof(bool),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("EsCopia", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<EsCopia>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);
            esCopia.AddAnnotation("Relational:ColumnName", "es_copia");
            esCopia.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var metodologiaReferencia = runtimeEntityType.AddProperty(
                "MetodologiaReferencia",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("MetodologiaReferencia", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<MetodologiaReferencia>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            metodologiaReferencia.AddAnnotation("Relational:ColumnName", "metodologia_referencia");
            metodologiaReferencia.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var muestraId = runtimeEntityType.AddProperty(
                "MuestraId",
                typeof(int),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("MuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<MuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            muestraId.AddAnnotation("Relational:ColumnName", "muestra_id");
            muestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var observaciones = runtimeEntityType.AddProperty(
                "Observaciones",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("Observaciones", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<Observaciones>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            observaciones.AddAnnotation("Relational:ColumnName", "observaciones");
            observaciones.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resColiformesTotales = runtimeEntityType.AddProperty(
                "ResColiformesTotales",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResColiformesTotales", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResColiformesTotales>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resColiformesTotales.AddAnnotation("Relational:ColumnName", "res_coliformes_totales");
            resColiformesTotales.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resEColi = runtimeEntityType.AddProperty(
                "ResEColi",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResEColi", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResEColi>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resEColi.AddAnnotation("Relational:ColumnName", "res_e_coli");
            resEColi.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resEstafilococosAureus = runtimeEntityType.AddProperty(
                "ResEstafilococosAureus",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResEstafilococosAureus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResEstafilococosAureus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resEstafilococosAureus.AddAnnotation("Relational:ColumnName", "res_estafilococos_aureus");
            resEstafilococosAureus.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resEsterilidadComercial = runtimeEntityType.AddProperty(
                "ResEsterilidadComercial",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResEsterilidadComercial", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResEsterilidadComercial>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resEsterilidadComercial.AddAnnotation("Relational:ColumnName", "res_esterilidad_comercial");
            resEsterilidadComercial.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resHongos = runtimeEntityType.AddProperty(
                "ResHongos",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResHongos", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResHongos>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resHongos.AddAnnotation("Relational:ColumnName", "res_hongos");
            resHongos.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resLevaduras = runtimeEntityType.AddProperty(
                "ResLevaduras",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResLevaduras", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResLevaduras>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resLevaduras.AddAnnotation("Relational:ColumnName", "res_levaduras");
            resLevaduras.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resListeriaMonocytogenes = runtimeEntityType.AddProperty(
                "ResListeriaMonocytogenes",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResListeriaMonocytogenes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResListeriaMonocytogenes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resListeriaMonocytogenes.AddAnnotation("Relational:ColumnName", "res_listeria_monocytogenes");
            resListeriaMonocytogenes.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resMicroorganismosAerobios = runtimeEntityType.AddProperty(
                "ResMicroorganismosAerobios",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResMicroorganismosAerobios", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResMicroorganismosAerobios>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resMicroorganismosAerobios.AddAnnotation("Relational:ColumnName", "res_microorganismos_aerobios");
            resMicroorganismosAerobios.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resPseudomonasSpp = runtimeEntityType.AddProperty(
                "ResPseudomonasSpp",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResPseudomonasSpp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResPseudomonasSpp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resPseudomonasSpp.AddAnnotation("Relational:ColumnName", "res_pseudomonas_spp");
            resPseudomonasSpp.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resRecuentoColiformes = runtimeEntityType.AddProperty(
                "ResRecuentoColiformes",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResRecuentoColiformes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResRecuentoColiformes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resRecuentoColiformes.AddAnnotation("Relational:ColumnName", "res_recuento_coliformes");
            resRecuentoColiformes.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var resSalmonellaSpp = runtimeEntityType.AddProperty(
                "ResSalmonellaSpp",
                typeof(string),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("ResSalmonellaSpp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<ResSalmonellaSpp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            resSalmonellaSpp.AddAnnotation("Relational:ColumnName", "res_salmonella_spp");
            resSalmonellaSpp.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { analisisMicroId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__Analisis__02BE43B19843BF37");

            var uQ__Analisis__1DEA25131E15622C = runtimeEntityType.AddIndex(
                new[] { muestraId },
                name: "UQ__Analisis__1DEA25131E15622C",
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MuestraId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("MuestraId") }),
                principalEntityType,
                unique: true,
                required: true);

            var muestra = declaringEntityType.AddNavigation("Muestra",
                runtimeForeignKey,
                onDependent: true,
                typeof(Muestra),
                propertyInfo: typeof(AnalisisMicrobiologico).GetProperty("Muestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisMicrobiologico).GetField("<Muestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var analisisMicrobiologico = principalEntityType.AddNavigation("AnalisisMicrobiologico",
                runtimeForeignKey,
                onDependent: false,
                typeof(AnalisisMicrobiologico),
                propertyInfo: typeof(Muestra).GetProperty("AnalisisMicrobiologico", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<AnalisisMicrobiologico>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Microbiologico_Muestras");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AnalisisMicrobiologico");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
