// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AnalisisFisicoquimicoEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.AnalisisFisicoquimico",
                typeof(AnalisisFisicoquimico),
                baseEntityType,
                propertyCount: 28,
                navigationCount: 1,
                foreignKeyCount: 1,
                namedIndexCount: 1,
                keyCount: 1);

            var analisisFqId = runtimeEntityType.AddProperty(
                "AnalisisFqId",
                typeof(int),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("AnalisisFqId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<AnalisisFqId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            analisisFqId.AddAnnotation("Relational:ColumnName", "analisis_fq_id");
            analisisFqId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var acidez = runtimeEntityType.AddProperty(
                "Acidez",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Acidez", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Acidez>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            acidez.AddAnnotation("Relational:ColumnName", "acidez");
            acidez.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            acidez.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var aptoConsumoHumano = runtimeEntityType.AddProperty(
                "AptoConsumoHumano",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("AptoConsumoHumano", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<AptoConsumoHumano>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            aptoConsumoHumano.AddAnnotation("Relational:ColumnName", "apto_consumo_humano");
            aptoConsumoHumano.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var cenizas = runtimeEntityType.AddProperty(
                "Cenizas",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Cenizas", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Cenizas>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            cenizas.AddAnnotation("Relational:ColumnName", "cenizas");
            cenizas.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            cenizas.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var cloroResidual = runtimeEntityType.AddProperty(
                "CloroResidual",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("CloroResidual", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<CloroResidual>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            cloroResidual.AddAnnotation("Relational:ColumnName", "cloro_residual");
            cloroResidual.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            cloroResidual.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var colorante = runtimeEntityType.AddProperty(
                "Colorante",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Colorante", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Colorante>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            colorante.AddAnnotation("Relational:ColumnName", "colorante");
            colorante.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var cumarina = runtimeEntityType.AddProperty(
                "Cumarina",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Cumarina", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Cumarina>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            cumarina.AddAnnotation("Relational:ColumnName", "cumarina");
            cumarina.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            cumarina.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var densidad = runtimeEntityType.AddProperty(
                "Densidad",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Densidad", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Densidad>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            densidad.AddAnnotation("Relational:ColumnName", "densidad");
            densidad.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            densidad.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dureza = runtimeEntityType.AddProperty(
                "Dureza",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Dureza", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Dureza>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            dureza.AddAnnotation("Relational:ColumnName", "dureza");
            dureza.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            dureza.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var extractoSeco = runtimeEntityType.AddProperty(
                "ExtractoSeco",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("ExtractoSeco", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<ExtractoSeco>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            extractoSeco.AddAnnotation("Relational:ColumnName", "extracto_seco");
            extractoSeco.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            extractoSeco.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fechaEntrega = runtimeEntityType.AddProperty(
                "FechaEntrega",
                typeof(DateOnly),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("FechaEntrega", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<FechaEntrega>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            fechaEntrega.AddAnnotation("Relational:ColumnName", "fecha_entrega");
            fechaEntrega.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fechaVencimiento = runtimeEntityType.AddProperty(
                "FechaVencimiento",
                typeof(DateOnly),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("FechaVencimiento", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<FechaVencimiento>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            fechaVencimiento.AddAnnotation("Relational:ColumnName", "fecha_vencimiento");
            fechaVencimiento.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fecula = runtimeEntityType.AddProperty(
                "Fecula",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Fecula", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Fecula>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            fecula.AddAnnotation("Relational:ColumnName", "fecula");
            fecula.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            fecula.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var gradoAlcoholico = runtimeEntityType.AddProperty(
                "GradoAlcoholico",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("GradoAlcoholico", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<GradoAlcoholico>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            gradoAlcoholico.AddAnnotation("Relational:ColumnName", "grado_alcoholico");
            gradoAlcoholico.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            gradoAlcoholico.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var humedad = runtimeEntityType.AddProperty(
                "Humedad",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Humedad", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Humedad>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            humedad.AddAnnotation("Relational:ColumnName", "humedad");
            humedad.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            humedad.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var indiceAcidez = runtimeEntityType.AddProperty(
                "IndiceAcidez",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("IndiceAcidez", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<IndiceAcidez>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            indiceAcidez.AddAnnotation("Relational:ColumnName", "indice_acidez");
            indiceAcidez.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            indiceAcidez.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var indiceRancidez = runtimeEntityType.AddProperty(
                "IndiceRancidez",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("IndiceRancidez", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<IndiceRancidez>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            indiceRancidez.AddAnnotation("Relational:ColumnName", "indice_rancidez");
            indiceRancidez.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            indiceRancidez.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var indiceRefraccion = runtimeEntityType.AddProperty(
                "IndiceRefraccion",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("IndiceRefraccion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<IndiceRefraccion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            indiceRefraccion.AddAnnotation("Relational:ColumnName", "indice_refraccion");
            indiceRefraccion.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            indiceRefraccion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var materiaGrasaCualitativa = runtimeEntityType.AddProperty(
                "MateriaGrasaCualitativa",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("MateriaGrasaCualitativa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<MateriaGrasaCualitativa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            materiaGrasaCualitativa.AddAnnotation("Relational:ColumnName", "materia_grasa_cualitativa");
            materiaGrasaCualitativa.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var materiaGrasaCuantitativa = runtimeEntityType.AddProperty(
                "MateriaGrasaCuantitativa",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("MateriaGrasaCuantitativa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<MateriaGrasaCuantitativa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            materiaGrasaCuantitativa.AddAnnotation("Relational:ColumnName", "materia_grasa_cuantitativa");
            materiaGrasaCuantitativa.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            materiaGrasaCuantitativa.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var muestraId = runtimeEntityType.AddProperty(
                "MuestraId",
                typeof(int),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("MuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<MuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            muestraId.AddAnnotation("Relational:ColumnName", "muestra_id");
            muestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var observaciones = runtimeEntityType.AddProperty(
                "Observaciones",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Observaciones", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Observaciones>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            observaciones.AddAnnotation("Relational:ColumnName", "observaciones");
            observaciones.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var otrasDeterminaciones = runtimeEntityType.AddProperty(
                "OtrasDeterminaciones",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("OtrasDeterminaciones", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<OtrasDeterminaciones>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            otrasDeterminaciones.AddAnnotation("Relational:ColumnName", "otras_determinaciones");
            otrasDeterminaciones.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var ph = runtimeEntityType.AddProperty(
                "Ph",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Ph", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Ph>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            ph.AddAnnotation("Relational:ColumnName", "ph");
            ph.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            ph.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pruebaEbar = runtimeEntityType.AddProperty(
                "PruebaEbar",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("PruebaEbar", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<PruebaEbar>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            pruebaEbar.AddAnnotation("Relational:ColumnName", "prueba_ebar");
            pruebaEbar.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var referencia = runtimeEntityType.AddProperty(
                "Referencia",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Referencia", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Referencia>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            referencia.AddAnnotation("Relational:ColumnName", "referencia");
            referencia.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var solidosTotales = runtimeEntityType.AddProperty(
                "SolidosTotales",
                typeof(decimal),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("SolidosTotales", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<SolidosTotales>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            solidosTotales.AddAnnotation("Relational:ColumnName", "solidos_totales");
            solidosTotales.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            solidosTotales.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tiempoCoccion = runtimeEntityType.AddProperty(
                "TiempoCoccion",
                typeof(string),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("TiempoCoccion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<TiempoCoccion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            tiempoCoccion.AddAnnotation("Relational:ColumnName", "tiempo_coccion");
            tiempoCoccion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { analisisFqId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__Analisis__A0EE283D85A555E5");

            var uQ__Analisis__1DEA251306E38FAF = runtimeEntityType.AddIndex(
                new[] { muestraId },
                name: "UQ__Analisis__1DEA251306E38FAF",
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MuestraId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("MuestraId") }),
                principalEntityType,
                unique: true,
                required: true);

            var muestra = declaringEntityType.AddNavigation("Muestra",
                runtimeForeignKey,
                onDependent: true,
                typeof(Muestra),
                propertyInfo: typeof(AnalisisFisicoquimico).GetProperty("Muestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AnalisisFisicoquimico).GetField("<Muestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var analisisFisicoquimico = principalEntityType.AddNavigation("AnalisisFisicoquimico",
                runtimeForeignKey,
                onDependent: false,
                typeof(AnalisisFisicoquimico),
                propertyInfo: typeof(Muestra).GetProperty("AnalisisFisicoquimico", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<AnalisisFisicoquimico>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Fisicoquimico_Muestras");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "AnalisisFisicoquimico");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
