// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class DevolucionMuestraEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.DevolucionMuestra",
                typeof(DevolucionMuestra),
                baseEntityType,
                propertyCount: 3,
                navigationCount: 1,
                foreignKeyCount: 1,
                namedIndexCount: 1,
                keyCount: 1);

            var devolucionId = runtimeEntityType.AddProperty(
                "DevolucionId",
                typeof(int),
                propertyInfo: typeof(DevolucionMuestra).GetProperty("DevolucionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DevolucionMuestra).GetField("<DevolucionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            devolucionId.AddAnnotation("Relational:ColumnName", "devolucion_id");
            devolucionId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var motivoDevolucion = runtimeEntityType.AddProperty(
                "MotivoDevolucion",
                typeof(string),
                propertyInfo: typeof(DevolucionMuestra).GetProperty("MotivoDevolucion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DevolucionMuestra).GetField("<MotivoDevolucion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            motivoDevolucion.AddAnnotation("Relational:ColumnName", "motivo_devolucion");
            motivoDevolucion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var muestraId = runtimeEntityType.AddProperty(
                "MuestraId",
                typeof(int),
                propertyInfo: typeof(DevolucionMuestra).GetProperty("MuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DevolucionMuestra).GetField("<MuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            muestraId.AddAnnotation("Relational:ColumnName", "muestra_id");
            muestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { devolucionId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__Devoluci__8E0C08B66FB58E25");

            var uQ__Devoluci__1DEA2513CD200D1A = runtimeEntityType.AddIndex(
                new[] { muestraId },
                name: "UQ__Devoluci__1DEA2513CD200D1A",
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MuestraId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("MuestraId") }),
                principalEntityType,
                unique: true,
                required: true);

            var muestra = declaringEntityType.AddNavigation("Muestra",
                runtimeForeignKey,
                onDependent: true,
                typeof(Muestra),
                propertyInfo: typeof(DevolucionMuestra).GetProperty("Muestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DevolucionMuestra).GetField("<Muestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var devolucionMuestra = principalEntityType.AddNavigation("DevolucionMuestra",
                runtimeForeignKey,
                onDependent: false,
                typeof(DevolucionMuestra),
                propertyInfo: typeof(Muestra).GetProperty("DevolucionMuestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<DevolucionMuestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Devolucion_Muestras");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "DevolucionMuestra");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
