// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class EstadoMuestraEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.EstadoMuestra",
                typeof(EstadoMuestra),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 1,
                namedIndexCount: 1,
                keyCount: 1);

            var estadoMuestraId = runtimeEntityType.AddProperty(
                "EstadoMuestraId",
                typeof(int),
                propertyInfo: typeof(EstadoMuestra).GetProperty("EstadoMuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EstadoMuestra).GetField("<EstadoMuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            estadoMuestraId.AddAnnotation("Relational:ColumnName", "estado_muestra_id");
            estadoMuestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var muestraEstado = runtimeEntityType.AddProperty(
                "MuestraEstado",
                typeof(string),
                propertyInfo: typeof(EstadoMuestra).GetProperty("MuestraEstado", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EstadoMuestra).GetField("<MuestraEstado>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            muestraEstado.AddAnnotation("Relational:ColumnName", "muestra_estado");
            muestraEstado.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { estadoMuestraId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__EstadoMu__F3A9A5A0C387BD16");

            var uQ__EstadoMu__ED79EA640A0373FD = runtimeEntityType.AddIndex(
                new[] { muestraEstado },
                name: "UQ__EstadoMu__ED79EA640A0373FD",
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "EstadoMuestra");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
