// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    public partial class LabDbContextModel
    {
        private LabDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c9fa1379-ced4-43c0-94b5-898d40309696"), entityTypeCount: 10)
        {
        }

        partial void Initialize()
        {
            var analisisFisicoquimico = AnalisisFisicoquimicoEntityType.Create(this);
            var analisisMicrobiologico = AnalisisMicrobiologicoEntityType.Create(this);
            var devolucionMuestra = DevolucionMuestraEntityType.Create(this);
            var estadoMuestra = EstadoMuestraEntityType.Create(this);
            var muestra = MuestraEntityType.Create(this);
            var muestraUsuarioRol = MuestraUsuarioRolEntityType.Create(this);
            var regionSalud = RegionSaludEntityType.Create(this);
            var solicitante = SolicitanteEntityType.Create(this);
            var tipoMuestra = TipoMuestraEntityType.Create(this);
            var usuario = UsuarioEntityType.Create(this);

            AnalisisFisicoquimicoEntityType.CreateForeignKey1(analisisFisicoquimico, muestra);
            AnalisisMicrobiologicoEntityType.CreateForeignKey1(analisisMicrobiologico, muestra);
            DevolucionMuestraEntityType.CreateForeignKey1(devolucionMuestra, muestra);
            MuestraEntityType.CreateForeignKey1(muestra, estadoMuestra);
            MuestraEntityType.CreateForeignKey2(muestra, regionSalud);
            MuestraEntityType.CreateForeignKey3(muestra, solicitante);
            MuestraEntityType.CreateForeignKey4(muestra, tipoMuestra);
            MuestraUsuarioRolEntityType.CreateForeignKey1(muestraUsuarioRol, muestra);
            MuestraUsuarioRolEntityType.CreateForeignKey2(muestraUsuarioRol, usuario);

            AnalisisFisicoquimicoEntityType.CreateAnnotations(analisisFisicoquimico);
            AnalisisMicrobiologicoEntityType.CreateAnnotations(analisisMicrobiologico);
            DevolucionMuestraEntityType.CreateAnnotations(devolucionMuestra);
            EstadoMuestraEntityType.CreateAnnotations(estadoMuestra);
            MuestraEntityType.CreateAnnotations(muestra);
            MuestraUsuarioRolEntityType.CreateAnnotations(muestraUsuarioRol);
            RegionSaludEntityType.CreateAnnotations(regionSalud);
            SolicitanteEntityType.CreateAnnotations(solicitante);
            TipoMuestraEntityType.CreateAnnotations(tipoMuestra);
            UsuarioEntityType.CreateAnnotations(usuario);

            AddAnnotation("ProductVersion", "10.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
