// <auto-generated />
using LabBackend.API.Data;
using LabBackend.API.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(LabDbContext), typeof(LabDbContextModel))]
