// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MuestraUsuarioRolEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.MuestraUsuarioRol",
                typeof(MuestraUsuarioRol),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 2,
                foreignKeyCount: 2,
                unnamedIndexCount: 1,
                namedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(MuestraUsuarioRol).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuestraUsuarioRol).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            id.AddAnnotation("Relational:ColumnName", "id");
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var asignadoEn = runtimeEntityType.AddProperty(
                "AsignadoEn",
                typeof(DateTime),
                propertyInfo: typeof(MuestraUsuarioRol).GetProperty("AsignadoEn", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuestraUsuarioRol).GetField("<AsignadoEn>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            asignadoEn.AddAnnotation("Relational:ColumnName", "asignado_en");
            asignadoEn.AddAnnotation("Relational:ColumnType", "datetime");
            asignadoEn.AddAnnotation("Relational:DefaultValueSql", "(getdate())");
            asignadoEn.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var muestraId = runtimeEntityType.AddProperty(
                "MuestraId",
                typeof(int),
                propertyInfo: typeof(MuestraUsuarioRol).GetProperty("MuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuestraUsuarioRol).GetField("<MuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            muestraId.AddAnnotation("Relational:ColumnName", "muestra_id");
            muestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var usuId = runtimeEntityType.AddProperty(
                "UsuId",
                typeof(int),
                propertyInfo: typeof(MuestraUsuarioRol).GetProperty("UsuId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuestraUsuarioRol).GetField("<UsuId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            usuId.AddAnnotation("Relational:ColumnName", "usu_id");
            usuId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__MuestraU__3213E83F65CB9472");

            var index = runtimeEntityType.AddIndex(
                new[] { usuId });

            var uQ_Muestra_Usuario = runtimeEntityType.AddIndex(
                new[] { muestraId, usuId },
                name: "UQ_Muestra_Usuario",
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("MuestraId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("MuestraId") }),
                principalEntityType,
                required: true);

            var muestra = declaringEntityType.AddNavigation("Muestra",
                runtimeForeignKey,
                onDependent: true,
                typeof(Muestra),
                propertyInfo: typeof(MuestraUsuarioRol).GetProperty("Muestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuestraUsuarioRol).GetField("<Muestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var muestraUsuarioRols = principalEntityType.AddNavigation("MuestraUsuarioRols",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<MuestraUsuarioRol>),
                propertyInfo: typeof(Muestra).GetProperty("MuestraUsuarioRols", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<MuestraUsuarioRols>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_MUR_Muestras");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("UsuId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("UsuId") }),
                principalEntityType,
                required: true);

            var usu = declaringEntityType.AddNavigation("Usu",
                runtimeForeignKey,
                onDependent: true,
                typeof(Usuario),
                propertyInfo: typeof(MuestraUsuarioRol).GetProperty("Usu", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(MuestraUsuarioRol).GetField("<Usu>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var muestraUsuarioRols = principalEntityType.AddNavigation("MuestraUsuarioRols",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<MuestraUsuarioRol>),
                propertyInfo: typeof(Usuario).GetProperty("MuestraUsuarioRols", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<MuestraUsuarioRols>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_MUR_Usuario");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "MuestraUsuarioRol");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
