// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class MuestraEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.Muestra",
                typeof(Muestra),
                baseEntityType,
                propertyCount: 23,
                navigationCount: 8,
                foreignKeyCount: 4,
                unnamedIndexCount: 4,
                namedIndexCount: 1,
                keyCount: 1);

            var muestraId = runtimeEntityType.AddProperty(
                "MuestraId",
                typeof(int),
                propertyInfo: typeof(Muestra).GetProperty("MuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<MuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            muestraId.AddAnnotation("Relational:ColumnName", "muestra_id");
            muestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var aspecto = runtimeEntityType.AddProperty(
                "Aspecto",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("Aspecto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Aspecto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            aspecto.AddAnnotation("Relational:ColumnName", "aspecto");
            aspecto.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var color = runtimeEntityType.AddProperty(
                "Color",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("Color", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Color>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            color.AddAnnotation("Relational:ColumnName", "color");
            color.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var condicionesRecepcion = runtimeEntityType.AddProperty(
                "CondicionesRecepcion",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("CondicionesRecepcion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<CondicionesRecepcion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            condicionesRecepcion.AddAnnotation("Relational:ColumnName", "condiciones_recepcion");
            condicionesRecepcion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var direccionToma = runtimeEntityType.AddProperty(
                "DireccionToma",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("DireccionToma", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<DireccionToma>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            direccionToma.AddAnnotation("Relational:ColumnName", "direccion_toma");
            direccionToma.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var dpsArea = runtimeEntityType.AddProperty(
                "DpsArea",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("DpsArea", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<DpsArea>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 150);
            dpsArea.AddAnnotation("Relational:ColumnName", "dps_area");
            dpsArea.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var enviadaPor = runtimeEntityType.AddProperty(
                "EnviadaPor",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("EnviadaPor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<EnviadaPor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 150);
            enviadaPor.AddAnnotation("Relational:ColumnName", "enviada_por");
            enviadaPor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var estadoMuestraId = runtimeEntityType.AddProperty(
                "EstadoMuestraId",
                typeof(int),
                propertyInfo: typeof(Muestra).GetProperty("EstadoMuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<EstadoMuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            estadoMuestraId.AddAnnotation("Relational:ColumnName", "estado_muestra_id");
            estadoMuestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fechaRecepcion = runtimeEntityType.AddProperty(
                "FechaRecepcion",
                typeof(DateOnly),
                propertyInfo: typeof(Muestra).GetProperty("FechaRecepcion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<FechaRecepcion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            fechaRecepcion.AddAnnotation("Relational:ColumnName", "fecha_recepcion");
            fechaRecepcion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var fechaToma = runtimeEntityType.AddProperty(
                "FechaToma",
                typeof(DateOnly),
                propertyInfo: typeof(Muestra).GetProperty("FechaToma", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<FechaToma>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateOnly(1, 1, 1));
            fechaToma.AddAnnotation("Relational:ColumnName", "fecha_toma");
            fechaToma.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var motivoSolicitud = runtimeEntityType.AddProperty(
                "MotivoSolicitud",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("MotivoSolicitud", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<MotivoSolicitud>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            motivoSolicitud.AddAnnotation("Relational:ColumnName", "motivo_solicitud");
            motivoSolicitud.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var muestraCodigoUnico = runtimeEntityType.AddProperty(
                "MuestraCodigoUnico",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("MuestraCodigoUnico", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<MuestraCodigoUnico>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            muestraCodigoUnico.AddAnnotation("Relational:ColumnName", "muestra_codigo_unico");
            muestraCodigoUnico.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var muestraNombre = runtimeEntityType.AddProperty(
                "MuestraNombre",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("MuestraNombre", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<MuestraNombre>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            muestraNombre.AddAnnotation("Relational:ColumnName", "muestra_nombre");
            muestraNombre.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var numLote = runtimeEntityType.AddProperty(
                "NumLote",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("NumLote", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<NumLote>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            numLote.AddAnnotation("Relational:ColumnName", "num_lote");
            numLote.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var numOficio = runtimeEntityType.AddProperty(
                "NumOficio",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("NumOficio", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<NumOficio>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            numOficio.AddAnnotation("Relational:ColumnName", "num_oficio");
            numOficio.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var olor = runtimeEntityType.AddProperty(
                "Olor",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("Olor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Olor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            olor.AddAnnotation("Relational:ColumnName", "olor");
            olor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var pesoNeto = runtimeEntityType.AddProperty(
                "PesoNeto",
                typeof(decimal),
                propertyInfo: typeof(Muestra).GetProperty("PesoNeto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<PesoNeto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0m);
            pesoNeto.AddAnnotation("Relational:ColumnName", "peso_neto");
            pesoNeto.AddAnnotation("Relational:ColumnType", "decimal(18, 4)");
            pesoNeto.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var regionId = runtimeEntityType.AddProperty(
                "RegionId",
                typeof(int),
                propertyInfo: typeof(Muestra).GetProperty("RegionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<RegionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            regionId.AddAnnotation("Relational:ColumnName", "region_id");
            regionId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var sabor = runtimeEntityType.AddProperty(
                "Sabor",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("Sabor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Sabor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            sabor.AddAnnotation("Relational:ColumnName", "sabor");
            sabor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var solicitanteId = runtimeEntityType.AddProperty(
                "SolicitanteId",
                typeof(int),
                propertyInfo: typeof(Muestra).GetProperty("SolicitanteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<SolicitanteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            solicitanteId.AddAnnotation("Relational:ColumnName", "solicitante_id");
            solicitanteId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var textura = runtimeEntityType.AddProperty(
                "Textura",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("Textura", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Textura>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            textura.AddAnnotation("Relational:ColumnName", "textura");
            textura.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tipoMuestraId = runtimeEntityType.AddProperty(
                "TipoMuestraId",
                typeof(int),
                propertyInfo: typeof(Muestra).GetProperty("TipoMuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<TipoMuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            tipoMuestraId.AddAnnotation("Relational:ColumnName", "tipo_muestra_id");
            tipoMuestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var tomadaPor = runtimeEntityType.AddProperty(
                "TomadaPor",
                typeof(string),
                propertyInfo: typeof(Muestra).GetProperty("TomadaPor", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<TomadaPor>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 150);
            tomadaPor.AddAnnotation("Relational:ColumnName", "tomada_por");
            tomadaPor.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { muestraId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__Muestras__1DEA251220CBB0DE");

            var index = runtimeEntityType.AddIndex(
                new[] { estadoMuestraId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { regionId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { solicitanteId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { tipoMuestraId });

            var uQ__Muestras__D86BDFABCFD871C4 = runtimeEntityType.AddIndex(
                new[] { muestraCodigoUnico },
                name: "UQ__Muestras__D86BDFABCFD871C4",
                unique: true);

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("EstadoMuestraId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("EstadoMuestraId") }),
                principalEntityType,
                required: true);

            var estadoMuestra = declaringEntityType.AddNavigation("EstadoMuestra",
                runtimeForeignKey,
                onDependent: true,
                typeof(EstadoMuestra),
                propertyInfo: typeof(Muestra).GetProperty("EstadoMuestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<EstadoMuestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var muestras = principalEntityType.AddNavigation("Muestras",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Muestra>),
                propertyInfo: typeof(EstadoMuestra).GetProperty("Muestras", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EstadoMuestra).GetField("<Muestras>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Muestras_Estado");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RegionId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("RegionId") }),
                principalEntityType,
                required: true);

            var region = declaringEntityType.AddNavigation("Region",
                runtimeForeignKey,
                onDependent: true,
                typeof(RegionSalud),
                propertyInfo: typeof(Muestra).GetProperty("Region", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Region>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var muestras = principalEntityType.AddNavigation("Muestras",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Muestra>),
                propertyInfo: typeof(RegionSalud).GetProperty("Muestras", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RegionSalud).GetField("<Muestras>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Muestras_Region");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SolicitanteId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("SolicitanteId") }),
                principalEntityType,
                required: true);

            var solicitante = declaringEntityType.AddNavigation("Solicitante",
                runtimeForeignKey,
                onDependent: true,
                typeof(Solicitante),
                propertyInfo: typeof(Muestra).GetProperty("Solicitante", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<Solicitante>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var muestras = principalEntityType.AddNavigation("Muestras",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Muestra>),
                propertyInfo: typeof(Solicitante).GetProperty("Muestras", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Solicitante).GetField("<Muestras>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Muestras_Solicitante");
            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey4(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TipoMuestraId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("TipoMuestraId") }),
                principalEntityType,
                required: true);

            var tipoMuestra = declaringEntityType.AddNavigation("TipoMuestra",
                runtimeForeignKey,
                onDependent: true,
                typeof(TipoMuestra),
                propertyInfo: typeof(Muestra).GetProperty("TipoMuestra", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Muestra).GetField("<TipoMuestra>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var muestras = principalEntityType.AddNavigation("Muestras",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Muestra>),
                propertyInfo: typeof(TipoMuestra).GetProperty("Muestras", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TipoMuestra).GetField("<Muestras>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            runtimeForeignKey.AddAnnotation("Relational:Name", "FK_Muestras_Tipo");
            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Muestras");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
