// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class SolicitanteEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.Solicitante",
                typeof(Solicitante),
                baseEntityType,
                propertyCount: 4,
                navigationCount: 1,
                keyCount: 1);

            var solicitanteId = runtimeEntityType.AddProperty(
                "SolicitanteId",
                typeof(int),
                propertyInfo: typeof(Solicitante).GetProperty("SolicitanteId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Solicitante).GetField("<SolicitanteId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            solicitanteId.AddAnnotation("Relational:ColumnName", "solicitante_id");
            solicitanteId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var solicitanteContacto = runtimeEntityType.AddProperty(
                "SolicitanteContacto",
                typeof(string),
                propertyInfo: typeof(Solicitante).GetProperty("SolicitanteContacto", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Solicitante).GetField("<SolicitanteContacto>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            solicitanteContacto.AddAnnotation("Relational:ColumnName", "solicitante_contacto");
            solicitanteContacto.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var solicitanteDireccion = runtimeEntityType.AddProperty(
                "SolicitanteDireccion",
                typeof(string),
                propertyInfo: typeof(Solicitante).GetProperty("SolicitanteDireccion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Solicitante).GetField("<SolicitanteDireccion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            solicitanteDireccion.AddAnnotation("Relational:ColumnName", "solicitante_direccion");
            solicitanteDireccion.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var solicitanteNombre = runtimeEntityType.AddProperty(
                "SolicitanteNombre",
                typeof(string),
                propertyInfo: typeof(Solicitante).GetProperty("SolicitanteNombre", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Solicitante).GetField("<SolicitanteNombre>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);
            solicitanteNombre.AddAnnotation("Relational:ColumnName", "solicitante_nombre");
            solicitanteNombre.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { solicitanteId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__Solicita__F52B1AF7DC5086BA");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Solicitante");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
