// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TipoMuestraEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.TipoMuestra",
                typeof(TipoMuestra),
                baseEntityType,
                propertyCount: 2,
                navigationCount: 1,
                namedIndexCount: 1,
                keyCount: 1);

            var tipoMuestraId = runtimeEntityType.AddProperty(
                "TipoMuestraId",
                typeof(int),
                propertyInfo: typeof(TipoMuestra).GetProperty("TipoMuestraId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TipoMuestra).GetField("<TipoMuestraId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            tipoMuestraId.AddAnnotation("Relational:ColumnName", "tipo_muestra_id");
            tipoMuestraId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var muestraTipo = runtimeEntityType.AddProperty(
                "MuestraTipo",
                typeof(string),
                propertyInfo: typeof(TipoMuestra).GetProperty("MuestraTipo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TipoMuestra).GetField("<MuestraTipo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100);
            muestraTipo.AddAnnotation("Relational:ColumnName", "muestra_tipo");
            muestraTipo.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { tipoMuestraId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__TipoMues__A0B23D97E6FDD1DD");

            var uQ__TipoMues__DB889C2717B4127F = runtimeEntityType.AddIndex(
                new[] { muestraTipo },
                name: "UQ__TipoMues__DB889C2717B4127F",
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TipoMuestra");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
