// <auto-generated />
using System;
using System.Reflection;
using LabBackend.API.Domain.Entities;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace LabBackend.API.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class UsuarioEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "LabBackend.API.Domain.Entities.Usuario",
                typeof(Usuario),
                baseEntityType,
                propertyCount: 5,
                navigationCount: 1,
                keyCount: 1);

            var usuId = runtimeEntityType.AddProperty(
                "UsuId",
                typeof(int),
                propertyInfo: typeof(Usuario).GetProperty("UsuId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<UsuId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            usuId.AddAnnotation("Relational:ColumnName", "usu_id");
            usuId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var usuContrasena = runtimeEntityType.AddProperty(
                "UsuContrasena",
                typeof(string),
                propertyInfo: typeof(Usuario).GetProperty("UsuContrasena", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<UsuContrasena>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 255);
            usuContrasena.AddAnnotation("Relational:ColumnName", "usu_contrasena");
            usuContrasena.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var usuCorreo = runtimeEntityType.AddProperty(
                "UsuCorreo",
                typeof(string),
                propertyInfo: typeof(Usuario).GetProperty("UsuCorreo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<UsuCorreo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 150);
            usuCorreo.AddAnnotation("Relational:ColumnName", "usu_correo");
            usuCorreo.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var usuNombre = runtimeEntityType.AddProperty(
                "UsuNombre",
                typeof(string),
                propertyInfo: typeof(Usuario).GetProperty("UsuNombre", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<UsuNombre>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 150);
            usuNombre.AddAnnotation("Relational:ColumnName", "usu_nombre");
            usuNombre.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var usuRol = runtimeEntityType.AddProperty(
                "UsuRol",
                typeof(string),
                propertyInfo: typeof(Usuario).GetProperty("UsuRol", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<UsuRol>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 50);
            usuRol.AddAnnotation("Relational:ColumnName", "usu_rol");
            usuRol.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { usuId });
            runtimeEntityType.SetPrimaryKey(key);
            key.AddAnnotation("Relational:Name", "PK__Usuario__430A673C9666B1C0");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Usuario");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
